### ISSUE TITLE
Make the README better

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/Hacktoberfest#9]

**Comment by lazyMonk1010** [comment]
Hey Dhanush! I want to work on this issue.  Want to update your Readme , Can you please Assign me this .

**Comment by Durgeshsejekar** [comment]
I want to work on this issue so please can you assign me .

**Comment by DhanushNehru** [comment]
Hi, @Durgeshsejekar , already @lazyMonk1010  is working on this issue

**Comment by lazyMonk1010** [comment]
hey Dhanush !! i have completed the issue , please check it.
